### ISSUE TITLE
QAE 第一期

### ISSUE THREAD

**Issue by bwangelme** [bwangelme/qae#1]
## QAE 是什么

Q App Engine

基于 K8S，让用户能够开发方便地发布应用

## 第一期目标

- [ ] 支持发布 Web 应用
- [ ] 支持发布 gRPC 应用
- [ ] 提供 qaecli 工具，让用户可以在终端中进行交互

## 基本概念

Name|说明
---|---
App|QAE中组织应用的基本单位
Task|一个 App 由多个 Task 构成，Task 可以是 web / gRPC 应用，未来还考虑支持 cron

### app.yaml

每个 App 都必须有一个 app.yaml 文件，用来配置应用，目前考虑有如下配置:

```yaml
appname: kubia
image: bwangel/qae_kubia_2021_12_02_1339:latest
# 配置文件，QAE 会将代码目录中的配置文件复制到镜像中
config:
      - config/store.yaml
tasks:
-    type: web
      name: master
      url: /
```

### 镜像

1. qae 不管 build 镜像。需要开发者自己 build 镜像并 push 到 docker hub 中。
2. qae 会提供基础 dockerfile

### Commit

由于资源不够，目前不考虑接入 Github 等 Git 仓库。开发者使用 `qae commit create` 创建 Commit。

Commit 目前包含如下属性

name|value
---|---
GitCommit|代码仓库的 Git
AppYAML|代码仓库中的 app.yaml

### Deploy

使用 `qae deploy <commit id>` 开始部署，QAE 会根据用户在 app.yaml 中的配置，创建对应的 k8s 资源。
